# Generated by Django 6.1.1 on 2026-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', help_text='Which collection the perfume is listed under.', max_length=10, verbose_name='For'),
        ),
    ]
